const data = {
  products: [
    {
      name: "Pop Shirt",
      slug: "pop-shirt",
      category: "Shirts",
      image: "/next-ecommerce/public/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 12,
      description: "bla bla bla bla... bla bla bla bla",
    },
    {
      name: "Cool Shirt",
      slug: "cool-shirt",
      category: "Shirts",
      image: "/next-ecommerce/public/images/shirt2.jpg",
      price: 88,
      brand: "Cosmo",
      rating: 4.2,
      numReviews: 18,
      countInStock: 2,
      description: "bla bla bla bla... bla bla bla bla",
    },
    {
      name: "Third Shirt",
      slug: "third-shirt",
      category: "Shirts",
      image: "/next-ecommerce/public/images/shirt3.jpg",
      price: 90,
      brand: "Cussi",
      rating: 5.0,
      numReviews: 9,
      countInStock: 20,
      description: "bla bla bla bla... bla bla bla bla",
    },
    {
      name: "Casual Shirt",
      slug: "casual-shirt",
      category: "Shirts",
      image: "../public/images/shirt4.jpg",
      price: 95,
      brand: "Cusual",
      rating: 5.0,
      numReviews: 20,
      countInStock: 7,
      description: "bla bla bla bla... bla bla bla bla",
    },
  ],
};
export default data;
